### ISSUE TITLE
mdrone data

### ISSUE THREAD

**Issue by mjk1376** [zhaoymn/mbeats#1]
Hello , i was interested your work and i want to test your results. when i want download your data file from dropbox in mdrone project the first zip downloaded correctly but second zip file it's not format of zip file and i can not open it . i try two time but i failed. i think it is problem of uploaded file. if you are able please correct it.
thanks

**Comment by MMWAVEMJK** [comment]
Hello, I opened first zip file in Winrar and Winrar show me error. The error was this file is corrupted. I think your uploaded file has been corrupted. how can i take files ? is it possible to upload every binary file separately in Dropbox? this will help in easy downloading and the files will not be corrupt.

**Comment by zhaoymn** [comment]
I can't replicate your error. Could you provide more details? The file is not corrupted, it was just cut into 2 pieces because of limitation of the size of a single file that can be uploaded to Dropbox. You have to have the two parts together to decompress. I do not use Winrar, I use 7z.
